In [1]:
!pip install pillow
!pip install numpy

In [2]:
from PIL import Image
import numpy as np

filename = 'image.png'
image = Image.open(filename)

image_array = np.array(image)
print(image_array)

[[[ 51  51  51]
  [ 51  51  51]
  [ 51  51  51]
  ...
  [ 51  51  51]
  [ 51  51  51]
  [ 51  51  51]]

 [[ 51  51  51]
  [ 51  51  51]
  [ 51  51  51]
  ...
  [ 51  51  51]
  [ 51  51  51]
  [ 51  51  51]]

 [[ 51  51  51]
  [ 51  51  51]
  [ 51  51  51]
  ...
  [ 51  51  51]
  [ 51  51  51]
  [ 51  51  51]]

 ...

 [[204 230 204]
  [204 230 204]
  [204 230 204]
  ...
  [212 192 192]
  [118  43  43]
  [249 236 236]]

 [[204 230 204]
  [204 230 204]
  [204 230 204]
  ...
  [220 204 204]
  [130  65  65]
  [245 210 210]]

 [[204 230 204]
  [204 230 204]
  [204 230 204]
  ...
  [215 206 206]
  [163 135 135]
  [231 174 174]]]


In [3]:
housing = np.array([[217, 181, 135],
                   [245, 220, 194]])

industry = np.array([223, 225, 255])

green_areas = np.array([[205, 230, 205],
                        [229, 235, 194],
                        [238, 242, 206],
                        [248, 252, 245]])

In [24]:
## brute kurea force ez
def count(color):
    counter = 0
    ir = lambda a, b: abs(a-b) < 4
    
    for column in image_array:
        for pixel in column:
            if (ir(pixel[0], column[0]) &
                ir(pixel[1], column[1]) &
                ir(pixel[2], column[2])).all():
                counter += 1
    return counter

def count_a(colors):
    counter = 0
    for color in colors:
        counter += count(color)
    return counter

In [30]:
# size of image
1864*931

1735384

In [31]:
print("RATES\nhousing=", count_a(housing), 
      "\nindustry=", count_a(industry), 
      "\ngreen_areas=", count_a(green_areas))

RATES
housing= 79258 
industry= 118887 
green_areas= 158516


In [ ]:
image2 = Image.open(filename)
image2_array = np.array(image2)

